# Generated by Django 4.0.1 on 2022-01-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_settings_client_clientlogo_client_taxnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('ریال', 'ریال'), ('دلار', 'دلار')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
