# Generated by Django 4.0.1 on 2022-01-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_product_currency_alter_settings_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('CURRENT', 'در جریان'), ('EMAIL_SENT', 'ایمیل ارسال شد'), ('OVERDUE', 'عقب افتاده'), ('PAID', 'پرداخت شده')], default='CURRENT', max_length=100),
        ),
    ]
