# Generated by Django 4.0.1 on 2022-01-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_client_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('ریال', 'ریال'), ('تومان', 'تومان')], default='ریال', max_length=100),
        ),
    ]
