# Generated by Django 4.0.1 on 2022-01-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_invoice_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='title',
            new_name='titile',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paymentTerms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='form_Number',
            field=models.CharField(blank=True, default='AF-07-03', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='request_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
