# Generated by Django 4.0.1 on 2022-01-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_rename_title_invoice_titile_remove_invoice_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='titile',
            new_name='title',
        ),
    ]
