# Generated by Django 4.0.1 on 2022-01-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_remove_invoice_product_product_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceRelated', to='invoice.invoice'),
        ),
    ]
