# Generated by Django 4.0.1 on 2022-01-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_alter_product_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
