# Generated by Django 4.0.1 on 2022-01-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_client_clientcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='create_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
