# Generated by Django 4.0.1 on 2022-02-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_alter_invoice_create_date_alter_invoice_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientWork',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
