# Generated by Django 4.0.1 on 2022-02-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_client_clientwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='addressLine1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientLogo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='client',
            name='province',
        ),
        migrations.RemoveField(
            model_name='client',
            name='taxNumber',
        ),
    ]
