# Generated by Django 4.0.1 on 2022-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_remove_client_addressline1_remove_client_clientlogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='addressLine1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='clientLogo',
            field=models.ImageField(default='default_logo.jpg', upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='taxNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientWork',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
